Repository bsideproject/moa-app, pull requests merged in 2023-06, with the labels that each got.

#16 refactor: refactor router
  lib/main.dart
  lib/navigations/main_bottom_tab.dart
  lib/providers/token_provider.dart
  lib/screens/edit_profile.dart
  lib/screens/file_sharing/file_sharing.dart
  lib/screens/sign_in.dart
  lib/services/fcm_service.dart
  lib/utils/router_config.dart
  lib/utils/router_provider.dart
  lib/utils/themes.dart
  test/test_utils.dart
  test/widgets/home_test.dart
Labels: ፦refactor

#19 style: font, color, text style 적용
  assets/fonts/Pretendard-Black.ttf
  assets/fonts/Pretendard-Bold.ttf
  assets/fonts/Pretendard-ExtraBold.ttf
  assets/fonts/Pretendard-ExtraLight.ttf
  assets/fonts/Pretendard-Light.ttf
  assets/fonts/Pretendard-Medium.ttf
  assets/fonts/Pretendard-Regular.ttf
  assets/fonts/Pretendard-SemiBold.ttf
  assets/fonts/Pretendard-Thin.ttf
  lib/constants/color_constants.dart
  lib/constants/font_constants.dart
  lib/constants/text_style_constants.dart
  lib/screens/file_sharing/user_listing_screen.dart
  lib/screens/permission_screen.dart
  lib/widgets/alert_dialog.dart
  lib/widgets/button.dart
  lib/widgets/edit_text.dart
  pubspec.yaml
Labels: style

#20 style: home ui 작업
  README.md
  assets/icons/folderIcon.png
  assets/icons/hashtag.png
  assets/icons/home.png
  assets/icons/setting.png
  assets/images/dooboolab.png
  assets/images/dooboolabBlack.png
  assets/images/folder.png
  assets/images/moaBannerImg.png
  assets/images/moaCommentImg.png
  assets/images/moaSwitchImg.png
  lib/constants/color_constants.dart
  lib/constants/file_constants.dart
  lib/constants/font_constants.dart
  lib/navigations/main_bottom_tab.dart
  lib/screens/edit_profile.dart
  lib/screens/file_sharing/user_listing_screen.dart
  lib/screens/home.dart
  lib/screens/home/home.dart
  lib/screens/home/widgets/collapsible_tab_scroll.dart
  lib/screens/home/widgets/folder_list.dart
  lib/screens/home/widgets/hashtag_list.dart
  lib/screens/home/widgets/moa_comment_img.dart
  lib/screens/permission_screen.dart
  lib/utils/router_provider.dart
  lib/widgets/alert_dialog.dart
  pubspec.lock
  pubspec.yaml
Labels: style

#21 bugfix: social login for web
  .env.sample
  android/app/src/main/AndroidManifest.xml
  lib/main.dart
  lib/navigations/main_bottom_tab.dart
  lib/repositories/auth_repository.dart
  lib/screens/sign_in.dart
  lib/utils/config.dart
  lib/utils/my_platform.dart
  lib/utils/router_provider.dart
  pubspec.lock
  pubspec.yaml
  web/index.html
Labels: 🛠 bugfix

#22 ci: Containerize moa-web with docker-compose.yml
  Dockerfile
  docker-compose.yml
  lib/main.dart
  nginx.conf
  pubspec.lock
  pubspec.yaml
Labels: 🎯 feature

#23 style: hashtag, hashtag 디테일 뷰 작업
  assets/icons/newestIcon.png
  assets/icons/searchIcon.png
  assets/images/emptyFolder.png
  ios/Podfile.lock
  lib/constants/color_constants.dart
  lib/constants/file_constants.dart
  lib/models/folder_model.dart
  lib/models/hashtag_model.dart
  lib/models/item_model.dart
  lib/navigations/main_bottom_tab.dart
  lib/providers/button_click_provider.dart
  lib/providers/item_provider.dart
  lib/screens/home/hashtag_detail.dart
  lib/screens/home/home.dart
  lib/screens/home/tab_view/folder_tab_view.dart
  lib/screens/home/tab_view/hashtag_tab_view.dart
  lib/screens/home/widgets/collapsible_tab_scroll.dart
  lib/screens/home/widgets/folder_list.dart
  lib/screens/home/widgets/hashtag_button.dart
  lib/screens/home/widgets/hashtag_list.dart
  lib/screens/home/widgets/moa_comment_img.dart
  lib/screens/item_detail.dart
  lib/screens/setting/setting.dart
  lib/utils/api.dart
  lib/utils/router_provider.dart
  lib/utils/themes.dart
  lib/widgets/app_bar.dart
  lib/widgets/button.dart
  lib/widgets/edit_text.dart
  pubspec.lock
Labels: style

#24 bugfix: 로그인시 riverpod 에러 뜨는 버그수정
  lib/providers/token_provider.dart
  lib/repositories/auth_repository.dart
  lib/screens/sign_in.dart
  lib/utils/api.dart
  pubspec.lock
  pubspec.yaml
Labels: 🛠 bugfix

#27 feat: grid_view 높이 동적변경 및 폴더뷰 작업
  assets/icons/arrowBack.png
  assets/icons/menu.png
  lib/constants/file_constants.dart
  lib/constants/font_constants.dart
  lib/models/folder_model.dart
  lib/repositories/folder_repository.dart
  lib/screens/file_sharing/user_listing_screen.dart
  lib/screens/home/folder_detail_view.dart
  lib/screens/home/hashtag_detail.dart
  lib/screens/home/hashtag_detail_view.dart
  lib/screens/home/home.dart
  lib/screens/home/tab_view/folder_tab_view.dart
  lib/screens/home/tab_view/hashtag_tab_view.dart
  lib/screens/home/widgets/dynamic_grid_view.dart
  lib/screens/home/widgets/hashtag_card.dart
  lib/screens/home/widgets/type_header.dart
  lib/screens/permission_screen.dart
  lib/screens/setting/setting.dart
  lib/utils/router_provider.dart
  lib/widgets/alert_dialog.dart
  lib/widgets/app_bar.dart
  lib/widgets/button.dart
  pubspec.lock
  pubspec.yaml
Labels: 🎯 feature, style

#28 bugfix: 앱 google login 튕기는 버그 수정
  lib/navigations/main_bottom_tab.dart
  lib/repositories/auth_repository.dart
  lib/screens/setting/setting.dart
  lib/widgets/app_bar.dart
  lib/widgets/button.dart
Labels: 🛠 bugfix

#29 style: bottom sheet ui 추가
  assets/icons/circleClose.png
  assets/icons/pencil.png
  assets/icons/share.png
  assets/icons/trash.png
  lib/constants/color_constants.dart
  lib/constants/file_constants.dart
  lib/navigations/main_bottom_tab.dart
  lib/screens/home/folder_detail_view.dart
  lib/screens/home/home.dart
  lib/screens/home/tab_view/folder_tab_view.dart
  lib/screens/home/tab_view/hashtag_tab_view.dart
  lib/screens/home/widgets/add_folder_bottom_sheet.dart
  lib/screens/home/widgets/dynamic_grid_view.dart
  lib/screens/home/widgets/hashtag_card.dart
  lib/screens/setting/setting.dart
  lib/utils/general.dart
  lib/utils/router_provider.dart
  lib/widgets/button.dart
  lib/widgets/edit_text.dart
Labels: style

#30 refactor: 사용하지 않는 코드 정리
  lib/generated/intl/messages_all.dart
  lib/generated/intl/messages_en.dart
  lib/generated/intl/messages_ko.dart
  lib/generated/l10n.dart
  lib/l10n/intl_en.arb
  lib/l10n/intl_ko.arb
  lib/main.dart
  lib/screens/result.dart
  lib/screens/sample.dart
  lib/utils/localization.dart
  lib/widgets/circle_loading_indicator.dart
  pubspec.lock
  pubspec.yaml
  test/mocks/http_client.dart
  test/mocks/http_client.mocks.dart
  test/mocks/navigator_observer.dart
  test/mocks/navigator_observer.mocks.dart
  test/test_utils.dart
Labels: ፦refactor

#32 style: setting 탭, 취향관리 화면 작업
  lib/constants/app_constants.dart
  lib/screens/home/folder_detail_view.dart
  lib/screens/home/hashtag_detail_view.dart
  lib/screens/home/home.dart
  lib/screens/home/tab_view/folder_tab_view.dart
  lib/screens/setting/edit_my_type_view.dart
  lib/screens/setting/setting.dart
  lib/screens/setting/widgets/setting_list_tile.dart
  lib/utils/router_provider.dart
  lib/widgets/app_bar.dart
  lib/widgets/dynamic_grid_list.dart
  lib/widgets/edit_text.dart
  lib/widgets/folder_list.dart
Labels: style
