Repository bsideproject/moa-app, pull requests merged in 2023-05, with the labels that each got.

#2 Feat/social login
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/kotlin/com/beside/moa/MainActivity.kt
  android/app/src/main/res/values/strings.xml
  android/build.gradle
  ios/Runner/AppDelegate.swift
  ios/Runner/Info.plist
  lib/main.dart
  lib/repositories/auth_repository.dart
  lib/screens/sign_in.dart
  lib/services/apis/google_sign_in_api.dart
  lib/services/apis/kakao_sigin_in_api.dart
  lib/services/apis/naver_sign_in_api.dart
  pubspec.lock
  pubspec.yaml
Labels: 🎯 feature

#4 feat: 외부에서 공유 받아오는 기능 구현
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/kotlin/com/beside/moa/MainActivity.kt
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  ios/Runner/RunnerDebug.entitlements
  ios/Share Extension/Base.lproj/MainInterface.storyboard
  ios/Share Extension/Info.plist
  ios/Share Extension/Share ExtensionDebug.entitlements
  ios/Share Extension/ShareViewController.swift
  lib/constants/app_constants.dart
  lib/constants/color_constants.dart
  lib/constants/dimens_constants.dart
  lib/constants/file_constants.dart
  lib/constants/font_constants.dart
  lib/models/content_model.dart
  lib/models/user_detail_model.dart
  lib/navigations/main_bottom_tab.dart
  lib/screens/edit_profile.dart
  lib/screens/file_sharing/file_sharing.dart
  lib/screens/file_sharing/user_listing_screen.dart
  lib/utils/constants.dart
  lib/utils/router_config.dart
  pubspec.lock
  pubspec.yaml
Labels: 🎯 feature

#6 refactor: auth_repository 리팩토링 및 공유하기 이슈 문제 인지
  ios/Podfile.lock
  ios/Runner/AppDelegate.swift
  ios/Runner/Info.plist
  lib/main.dart
  lib/models/user_model.dart
  lib/repositories/auth_repository.dart
  lib/screens/sign_in.dart
  lib/services/apis/google_sign_in_api.dart
  lib/services/apis/kakao_sigin_in_api.dart
  lib/services/apis/naver_sign_in_api.dart
  lib/utils/config.dart
  pubspec.lock
  pubspec.yaml
Labels: ፦refactor, 🎯 feature

#7 feat: dio baseUrl 세팅 및 로그인 일부 api 연결
  .vscode/settings.json
  README.md
  lib/main.dart
  lib/providers/item_provider.dart
  lib/providers/token_provider.dart
  lib/providers/user_provider.dart
  lib/repositories/auth_repository.dart
  lib/repositories/item_repository.dart
  lib/repositories/non_member_repository.dart
  lib/repositories/token_repository.dart
  lib/screens/edit_profile.dart
  lib/screens/home.dart
  lib/screens/sign_in.dart
  lib/utils/api.dart
  lib/utils/config.dart
  test/widgets/home_test.dart
Labels: 🎯 feature

#8 feat: iOS google 로그인 세팅
  ios/.gitignore
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  lib/main.dart
  lib/repositories/auth_repository.dart
  lib/screens/edit_profile.dart
  lib/utils/router_config.dart
  lib/widgets/alert_dialog.dart
  lib/widgets/custom_checkbox.dart
Labels: 🎯 feature

#9 feat/secure storage
  .gitignore
  android/app/build.gradle
  android/build.gradle
  ios/Podfile.lock
  lib/main.dart
  lib/repositories/token_repository.dart
  pubspec.lock
  pubspec.yaml
Labels: 🎯 feature

#11 feat: firebase fcm 세팅
  .fvm/fvm_config.json
  .gitignore
  android/.gitignore
  android/app/build.gradle
  android/app/src/main/res/drawable/app_icon.png
  android/build.gradle
  ios/.gitignore
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/GoogleService-Info.plist
  ios/Runner/Info.plist
  ios/Runner/RunnerDebug.entitlements
  ios/firebase_app_id_file.json
  lib/firebase_options.dart
  lib/main.dart
  lib/repositories/auth_repository.dart
  lib/screens/home.dart
  lib/screens/sign_in.dart
  lib/services/apis/sample.dart
  lib/services/fcm_service.dart
  lib/utils/config.dart
  pubspec.lock
  pubspec.yaml
  test/widgets/home_test.dart
  web/firebase-messaging-sw.js
Labels: 🎯 feature, issue

#14 refactor: refactor fcm_service
  lib/main.dart
  lib/screens/home.dart
  lib/services/fcm_service.dart
  lib/utils/router_config.dart
Labels: ፦refactor
